<?php
/**
 * Plugin functions.
 *
 * @package A2UIWP
 */

declare(strict_types = 1);

namespace A2UIWP;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

const PAGE_SLUG = 'a2ui-wp';

/**
 * Registers the scripts and styles the plugin ships.
 *
 * Registered on `init` rather than enqueued outright, so that anything else
 * wanting to put an A2UI surface on a screen of its own can enqueue the same
 * handle instead of a second copy of the renderer.
 *
 * @return void
 */
function register_assets(): void {
	$asset = get_asset_meta( 'admin' );

	wp_register_script(
		'a2ui-wp-admin',
		plugins_url( 'build/admin.js', A2UI_WP_FILE ),
		$asset['dependencies'],
		$asset['version'],
		[ 'strategy' => 'defer' ]
	);

	wp_set_script_translations( 'a2ui-wp-admin', 'a2ui-wp' );

	wp_register_style(
		'a2ui-wp-admin',
		plugins_url( 'build/admin.css', A2UI_WP_FILE ),
		[ 'wp-components' ],
		$asset['version']
	);

	wp_style_add_data( 'a2ui-wp-admin', 'rtl', 'replace' );
}

/**
 * Returns the build metadata for a given entry point.
 *
 * @param string $handle Entry point name.
 * @return array{dependencies: non-empty-string[], version: string} Asset metadata.
 */
function get_asset_meta( string $handle ): array {
	$asset_file = A2UI_WP_DIR . "/build/$handle.asset.php";

	/**
	 * Asset metadata as generated by the build.
	 *
	 * The dependencies are the handles of the scripts the entry point imports,
	 * as the dependency extraction plugin emits them.
	 *
	 * @var array{dependencies?: non-empty-string[], version?: string} $asset
	 */
	$asset = is_readable( $asset_file ) ? require $asset_file : [];

	return [
		'dependencies' => $asset['dependencies'] ?? [],
		'version'      => $asset['version'] ?? VERSION,
	];
}

/**
 * Adds the playground page under Tools.
 *
 * Tools rather than a top-level entry: the page is a place to try the
 * renderer against sample streams, not a feature people use every day.
 *
 * @return void
 */
function add_admin_menu(): void {
	add_management_page(
		__( 'A2UI', 'a2ui-wp' ),
		__( 'A2UI', 'a2ui-wp' ),
		'manage_options',
		PAGE_SLUG,
		__NAMESPACE__ . '\render_admin_page'
	);
}

/**
 * Returns the hook suffix of the playground page, if it was registered.
 *
 * `add_management_page()` returns the hook suffix on registration and
 * `false` when the current user may not see the page, so this is computed
 * rather than remembered, and gives the same answer on every call.
 *
 * @return string Hook suffix, or an empty string when the page is not available.
 */
function get_admin_page_hook(): string {
	return (string) get_plugin_page_hookname( PAGE_SLUG, 'tools.php' );
}

/**
 * Enqueues the playground on its own page and nowhere else.
 *
 * @param string $hook_suffix The current admin page.
 * @return void
 */
function enqueue_admin_assets( string $hook_suffix ): void {
	if ( get_admin_page_hook() !== $hook_suffix ) {
		return;
	}

	wp_enqueue_script( 'a2ui-wp-admin' );
	wp_enqueue_style( 'a2ui-wp-admin' );
}

/**
 * Renders the playground page.
 *
 * Nothing but a mount point: the page is a React application, and the
 * messages it renders are part of the bundle.
 *
 * @return void
 */
function render_admin_page(): void {
	?>
	<div class="wrap">
		<h1 class="screen-reader-text"><?php esc_html_e( 'A2UI', 'a2ui-wp' ); ?></h1>
		<div id="a2ui-wp-root" class="a2ui-wp-playground"></div>
	</div>
	<?php
}
